name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/cloudflare-dns-update
          tag_name: ${{ github.event.release.tag_name }}
